### ISSUE TITLE
Infografía-Gestion de Proyectos

### ISSUE THREAD

**Issue by Brisa-4** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Brisa-4#2]
[Infografía GDP.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Brisa-4/files/9420539/Infografia.GDP.pdf)

**Comment by Ferch0419** [comment]
Excelente trabajo: 20/20.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
